# Generated by Django 5.0.3 on 2024-03-26 13:01

import django.core.validators
import django.db.models.deletion
import validators.number_car_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, validators=[validators.number_car_validator.validate_custom_number], verbose_name='Номер')),
                ('lifting_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('now_location', models.ForeignKey(default=14601, on_delete=django.db.models.deletion.PROTECT, related_name='now_location', to='location.locationmodel', verbose_name='Текущая локация')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'db_table': 'car_car',
            },
        ),
    ]
