# Generated by Django 5.0.3 on 2024-03-26 11:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='location.locationmodel')),
                ('location_pick_up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_up', to='location.locationmodel')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'db_table': 'cargo_cargo',
            },
        ),
    ]
